language: php
php:
  - 5.4
before_script:
  - composer selfupdate
  - composer install --dev
  - composer require --dev phpunit/phpunit 3.7.18
  - wget https://scrutinizer-ci.com/ocular.phar
script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover --configuration="phpunit.xml"
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
