language: php
php:
  - 5.4
  - 5.3
before_script:
  - composer install
script:
  - phpunit --bootstrap=bootstrap.php --coverage-text="php://stdout" --configuration="phpunit.xml" src/Navarr/Socket/Tests