language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
before_script:
  - composer selfupdate
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar
script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover --configuration="phpunit.xml"
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
